jobs:
###########################################################
# Builds
###########################################################
- job: LinuxBuilds
  # Host Box
  pool:
    vmImage: 'ubuntu-20.04'
  # Docker Images
  strategy:
    matrix:
      ubuntu18:
        image: tfcollins/test-ubuntu:20.04
  container: $[ variables['image'] ]
  steps:
  - script: |
      sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git cmake doxygen graphviz libaio-dev libusb-1.0-0-dev libserialport-dev libavahi-client-dev rpm tar bzip2 gzip
    displayName: "Setup Ubuntu"
    condition: contains(variables['image'], 'ubuntu')

  - script: |
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libxml2 libxml2-dev bison flex libboost-all-dev
      git clone https://github.com/analogdevicesinc/libiio.git
      cd libiio
      mkdir build && cd build
      cmake ..
      make
      sudo make install
      sudo ldconfig
      cd ../..
      rm -rf libiio
    displayName: Install libiio-iio

  - script: |
      git clone https://github.com/analogdevicesinc/libad9361-iio.git
      cd libad9361-iio
      mkdir build && cd build
      cmake ..
      make
      sudo make install
      sudo ldconfig
      cd ../..
      rm -rf libad9361-iio
    displayName: Install libad9361-iio

  - script: |
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgmp-dev swig gnuradio gnuradio-dev
      mkdir build && cd build
      cmake ..
      make
      cd ..
    displayName: Build

###########################################################
# Deploy
###########################################################
