/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(converter_ss.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1383b3019a88ca030c2e699f8f6e1499)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iio/converter_ss.h>
// pydoc.h is automatically generated in the build directory
#include <converter_ss_pydoc.h>

void bind_converter_ss(py::module& m)
{

    using converter_ss    = ::gr::iio::converter_ss;


    py::class_<converter_ss, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<converter_ss>>(m, "converter_ss", D(converter_ss))

        .def(py::init(&converter_ss::make),
           py::arg("channel"),
           py::arg("inverse"),
           D(converter_ss,make)
        )
        



        ;




}







