/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(math.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(304e94cfad266035830cafb9f5b1cca2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iio/math.h>
// pydoc.h is automatically generated in the build directory
#include <math_pydoc.h>

void bind_math(py::module& m)
{

    using iio_math    = ::gr::iio::iio_math;
    using iio_math_gen    = ::gr::iio::iio_math_gen;


    py::class_<iio_math, gr::hier_block2,
        std::shared_ptr<iio_math>>(m, "iio_math", D(iio_math))

        .def(py::init(&iio_math::make),
           py::arg("function"),
           py::arg("ninputs") = 1,
           D(iio_math,make)
        )
        



        ;


    py::class_<iio_math_gen, gr::hier_block2,
        std::shared_ptr<iio_math_gen>>(m, "iio_math_gen", D(iio_math_gen))

        .def(py::init(&iio_math_gen::make),
           py::arg("sampling_freq"),
           py::arg("wav_freq"),
           py::arg("function"),
           D(iio_math_gen,make)
        )
        



        ;




}







