#!/bin/sh -e

. ci/travis/lib.sh

PYTHON_VER=3

handle_centos() {
	# First EPEL stuff
	yum install -y epel-release

	# Only CentOS 8 and higher

	yum -y groupinstall 'Development Tools'
	yum -y install yum-utils
	yum config-manager --set-enabled powertools

	yum -y install cmake boost-devel fftw-devel bison flex yum \
		swig git libusb1-devel doxygen libaio-devel avahi-devel bzip2 gzip \
		rpm rpm-build libxml2-devel gmp-devel log4cpp-devel mpir-devel \
		gnuradio-devel python${PYTHON_VER}-devel

	if [ -n "$PACKAGE_TO_INSTALL" ] ; then
		sudo yum localinstall -y $PACKAGE_TO_INSTALL
		STAGINGDIR=/usr
	elif [ "$INSTALL_FROM_SW_DOWNLOADS" = "1" ] ; then
		for pkg in libiio libad9361-iio ; do
			wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.rpm
			sudo yum localinstall -y ./${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.rpm
		done
	fi
}

handle_generic_docker() {
	prepare_docker_image
}

handle_default() {
	sudo apt-get -qq update
	sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libboost-dev bison doxygen \
		flex git libfftw3-dev swig cmake libaio-dev libavahi-client-dev libavahi-common-dev \
		libusb-1.0-0-dev libxml2-dev tar bzip2 gzip \
		libserialport-dev gnuradio-dev libpython${PYTHON_VER}-dev

	if [ -n "$PACKAGE_TO_INSTALL" ] ; then
		sudo dpkg -i $PACKAGE_TO_INSTALL
	elif [ "$INSTALL_FROM_SW_DOWNLOADS" = "1" ] ; then
		for pkg in libiio libad9361-iio ; do
			wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.deb
			sudo dpkg -i ./${LIBIIO_BRANCH}_latest_${pkg}${LDIST}.deb
		done
	fi
}

handle_ubuntu() {
	handle_default
}

handle_debian() {
	handle_default
}

setup_build_type_env_vars

handle_${BUILD_TYPE}
