#!/bin/sh -e

. ci/travis/lib.sh

handle_default() {
	mkdir -p build
	cd build
	cmake ..
	make
	cd ..
}

handle_centos() {
	handle_default
}

handle_ubuntu() {
	handle_default
}

handle_debian() {
	handle_default
}

handle_generic_docker() {
	run_docker_script inside_docker.sh
}

setup_build_type_env_vars

handle_${BUILD_TYPE}
