#!/bin/sh -e

. ci/travis/lib.sh

handle_default() {
	mkdir -p build
	cd build
	cmake ..
	make
	cd ..
}

handle_centos() {
	handle_default
}

handle_centos_docker() {
        run_docker_script inside_docker.sh \
                "centos:centos${OS_VERSION}" "centos"
}

handle_ubuntu_docker() {
        run_docker_script inside_docker.sh \
                "ubuntu:${OS_VERSION}"
}

LIBNAME="gr-iio"
OS_TYPE=${1:-default}
OS_VERSION="$2"

handle_${OS_TYPE}
